name = "stellar-badge-discord-bot"
main = "src/index.ts"
compatibility_date = "2023-02-08"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = ""
database_id = ""
preview_database_id = ""